package edu.buffalo.cse.cse486586.simpledynamo;

public enum MessageType {
	INSERT, QUERY_REQUEST, DELETE_REQUEST, QUERY_REQUEST_ALL, DELETE_REQUEST_ALL,
	QUERY_RESPONSE, QUERY_RESPONSE_ALL, SYNC_REQUEST_PREDECESSORS, SYNC_REQUEST_SUCESSORS, SYNC_RESPONSE, PING_RESPONSE
}
